### ISSUE TITLE
Figuring out how to get this working on Heroku

### ISSUE THREAD

**Issue by BLCKPSTV** [vkosuri/chatterbot-live-example#2]
Again not really an issue but can't find where to put my questions?

I get this error when typing:
heroku ps:scale web=0
Scaling dynos... !
 ▸    Couldn't find that process type.

And this when checking the log files. 

 heroku logs -t

2017-04-14T18:25:02.884630+00:00 heroku[router]: at=info code=H81 desc="Blank app" method=GET path="/" host=sleepy-hollows-66889.herokuapp.com request_id=c8c68ba9-7848-4e7a-ab50-15f56ab69c11 fwd="213.49.99.194" dyno= connect= service= status=502 bytes= protocol=https

Any idea what I'm doing wrong, my github pages looks exactly like the one you have and is connected and linked via the python tutorial on heroku. 

https://github.com/BLCKPSTV/theloneliestmonk/tree/master

**Comment by BLCKPSTV** [comment]
Small update! I've instead of recreating it started a project from your cloned page. 
And get following error.

`DisallowedHost at /
Invalid HTTP_HOST header: 'pacific-beach-29903.herokuapp.com'. You may need to add u'pacific-beach-29903.herokuapp.com' to ALLOWED_HOSTS.
Request Method:	GET
Request URL:	https://pacific-beach-29903.herokuapp.com/
Django Version:	1.11
Exception Type:	DisallowedHost
Exception Value:	
Invalid HTTP_HOST header: 'pacific-beach-29903.herokuapp.com'. You may need to add u'pacific-beach-29903.herokuapp.com' to ALLOWED_HOSTS.
Exception Location:	/app/.heroku/python/lib/python2.7/site-packages/django/http/request.py in get_host, line 113
Python Executable:	/app/.heroku/python/bin/python
Python Version:	2.7.13
Python Path:	
['/app',
 '/app/.heroku/python/bin',
 '/app',
 '/app/.heroku/python/lib/python27.zip',
 '/app/.heroku/python/lib/python2.7',
 '/app/.heroku/python/lib/python2.7/plat-linux2',
 '/app/.heroku/python/lib/python2.7/lib-tk',
 '/app/.heroku/python/lib/python2.7/lib-old',
 '/app/.heroku/python/lib/python2.7/lib-dynload',
 '/app/.heroku/python/lib/python2.7/site-packages']
Server time:	Fri, 14 Apr 2017 18:35:55 +0000`

**Comment by BLCKPSTV** [comment]
I can't figure out how to get this to work! Any help would be awesome..

**Comment by vkosuri** [comment]
@BLCKPSTV  sorry for delay response look into your issue

**Comment by vkosuri** [comment]
your setting should be like this

``` Django
# SECURITY WARNING: keep the secret key used in production secret!              
SECRET_KEY = 'fsch+6!=q+@ol&%0x!nwdl@48^ixbd4clx5f1i!5n^66y+pmn*'
# SECURITY WARNING: don't run with debug turned on in production!            
DEBUG = True
ALLOWED_HOSTS = ['127.0.0.1', 'pacific-beach-29903.herokuapp.com']
```

**Comment by BLCKPSTV** [comment]
Perfect!! It shows the chatterbot on my heroku open web page!
Thouhg the bot doesn't work! I'll open a new issue when I find out why it isn't working! Or when I'm stuck figuring it out.
