### ISSUE TITLE
Is there any option to train data from sql table

### ISSUE THREAD

**Issue by PoojaPatel05** [vkosuri/chatterbot-live-example#5]
i want to train data which is stored in mysql databse. data is in mysqlyog.

**Comment by vkosuri** [comment]
You have to export your data either JSON or YAML from MySQL to train your bot, https://stackoverflow.com/a/5036634/358458

**Comment by PoojaPatel05** [comment]
what if I give a path of my data database in (\chatterbot-live-example-master\example_app\settings.py) in below given part of the code. 
`CHATTERBOT = {
    'name': 'Django ChatterBot Example',
    'logic_adapters' : [
        "chatterbot.logic.BestMatch"
    ],
    'trainer': 'chatterbot.trainers.ChatterBotCorpusTrainer',
    'training_data': [
        'chatterbot.corpus'
        (here the path of database )
    ]
}`

**Comment by vkosuri** [comment]
I think this could help you http://chatterbot.readthedocs.io/en/stable/training.html#specifying-corpus-scope

**Comment by PoojaPatel05** [comment]
this are for string and txt, .yml, .json file. But I want to train mysql table or database

**Comment by PoojaPatel05** [comment]
I want to make an API. I have trained the database table. now I want to ask question in postman and it should give answer related to question ID.

**Comment by PoojaPatel05** [comment]
got it. Thank you so much
