### ISSUE TITLE
while using mysql it is showing error.

### ISSUE THREAD

**Issue by PoojaPatel05** [vkosuri/chatterbot-live-example#6]
I have changed this line in settings.py line number 82.
`'ENGINE': 'django.db.backends.mysql',`
because I want to use mysql database to train the bot.
But it is showing showing this error. `django.db.utils.OperationalError: (1045, "Access denied for user 'ODBC'@'localhost' (using password: NO)")`
what is the solution for this?

**Comment by vkosuri** [comment]
I hope these instructions will solve your problem https://stackoverflow.com/a/11170252/358458

**Comment by PoojaPatel05** [comment]
solved it. thank you so much
